### ISSUE TITLE
Can this tab component achieve independent data operation like a browser-like tab?

### ISSUE THREAD

**Issue by xiaomao996688** [brrd/electron-tabs#108]
Can this tab component achieve independent data operation like a browser-like tab?

**Comment by brrd** [comment]
I don't understand the question. What is "independent data operation"? What do you expect exactly?

**Comment by xiaomao996688** [comment]
> I don't understand the question. What is "independent data operation"? What do you expect exactly?
The data stored in LocalStorage is not shared by other tabs. The url address of this src attribute, can you jump to the subpage of this url, let tabGroup = new TabGroup();
let tab = tabGroup.addTab({
   title: "Electron",
   src: "http://electron.atom.io",
   visible: true
}); For example: src :http://localhost:8080. The src in this tab jumps to localhost:8080/home/b343011e

**Comment by brrd** [comment]
electron-tabs uses standard Electron webviews under the hood, so the the documentation about webviews apply to electron-tabs. This page should answer most of your questions: https://www.electronjs.org/docs/api/webview-tag

About localStorage now, if your webviews share the same session (which is the default), then the localStorage is supposed to be the same for all your tabs. By instance, I got this in a fresh electron-tab demo:

![image](https://user-images.githubusercontent.com/7335302/88146886-c1b0ad80-cbfc-11ea-896f-65ba56d699ca.png)

Keep in mind that localStorage is always specific to a domain, so you won't be able to share localStorage information between two different domains. In my example, this does not work because brrd.fr and google.com are not the same domain:

![image](https://user-images.githubusercontent.com/7335302/88147210-34ba2400-cbfd-11ea-99bd-aaa24f745bcb.png)

Hope this helps.

**Comment by HansLanger** [comment]
To give a different context for each tab use "partition":

` initWebview: function () {
    const webview = this.webview = document.createElement("webview");
    webview.useragent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"
    **webview.partition = "persist:page" + this.id;**`


More info here: [https://www.electronjs.org/docs/api/webview-tag](url)
