### ISSUE TITLE
How to send data to a tab?

### ISSUE THREAD

**Issue by ShlomiRex** [brrd/electron-tabs#113]
Title
I want to give some data to tab, so when it loads json inside the html, it can read the data

**Comment by brrd** [comment]
Webviews behave the same than electron webviews, so you can refer to the official documentation: https://electronjs.org/docs/api/webview-tag

If you have access to the page loaded into the webview then you can simply add a `<script>` tag in this page. Otherwise use:

```javascript
tabGroup.addTab({
  webviewAttributes: {
    preload: "./test.js"
  }
});
```

as described in: https://electronjs.org/docs/api/webview-tag#preload
