### ISSUE TITLE
electron-context-menu and electron-devtools-installer not propagated to webview tabs

### ISSUE THREAD

**Issue by patarapolw** [brrd/electron-tabs#115]
**Describe the bug**

electron-context-menu (https://github.com/sindresorhus/electron-context-menu/issues/129) and VUEJS_DEVTOOLS (https://github.com/MarshallOfSound/electron-devtools-installer) don't install inside webview tabs.

However, when I make it load the tab contents directly, everything works perfectly fine.

**To Reproduce**

```ts
import ContextMenu from 'electron-context-menu'
import installExtension, { VUEJS_DEVTOOLS } from 'electron-devtools-installer'

ContextMenu()

app.on('ready', async () => {
  if (isDevelopment && !process.env.IS_TEST) {
    // Install Vue Devtools
    try {
      await installExtension(VUEJS_DEVTOOLS)
    } catch (e) {
      console.error('Vue Devtools failed to install:', e.toString())
    }
  }
  createWindow()
})
```

etabs.html

```html
        tabGroup.addTab({
          title: 'Home',
          src: `/index.html?token=${token}#` + '/',
          active: true,
          closable: false,
          webviewAttributes: {
            preload,
            nodeintegration,
            plugins: ''
          }
        })
```

**Expected behavior**

electron-context-menu and electron-devtools-installer propagates to webview tabs

**Please complete the following information**
 - OS: Xubuntu 20.04
 - electron-tabs version: 0.15.0
 - Electron version: 11.2.0

**Code**

https://github.com/zhquiz/e-zhquiz/tree/electron-vue

**Comment by brrd** [comment]
This issue is obviously related to those libraries, which seem to poorly support webview integration, more than to electron-tabs itself.

You should maybe try this solution with electron-context-menu: https://github.com/sindresorhus/electron-context-menu/issues/37#issuecomment-628657983

However electron-devtools-installer obviously doesn't work in webviews: https://github.com/MarshallOfSound/electron-devtools-installer/issues/129

I'm closing this issue since we can't do anything to make such libraries work in tabs if they don't support webviews.

**Comment by patarapolw** [comment]
Sadly, both electron-context-menu and devtools don't work for me, despite suggested solutions.
