### ISSUE TITLE
If it is forbidden to open new windows

### ISSUE THREAD

**Issue by aaxx255** [brrd/electron-tabs#122]
```js
newtab.webContents.on('new-window', (event, url, frameName, disposition) => {
  /** @params {string} disposition
  *  new-window : window.open
  *  background-tab: command+click
  *  foreground-tab: target _blank
  * /
})
```

Can not work, can not get url parameters.

**Comment by brrd** [comment]
I edited you message to make it readable. Please take care of your code formatting.

`newtab.webContents` doesn't exist. Only `tab.webview` is defined as you can read it in the documentation. 

I don't know what you are trying to do exactly, but your issue seems to be related to Electron. Please check Electron documentation to read about the difference between webview and webcontents, and how to access the latest in you application. I'm closing this issue since it is out of the scope of this project.
