### ISSUE TITLE
right sliding bar

### ISSUE THREAD

**Issue by hz2018tv** [brrd/electron-tabs#170]
a right sliding bar is added by using tabs. please see attached pics.
![screen-no-tab](https://user-images.githubusercontent.com/44717154/201403090-5507d790-9671-4fb9-951c-d0cc02873f54.png)
![screen-tab](https://user-images.githubusercontent.com/44717154/201403097-cb4aafc0-425f-4232-acd7-da8af885065f.png)

**Comment by brrd** [comment]
I can't reproduce. Please give some sample code.

**Comment by hz2018tv** [comment]
[cs1.zip](https://github.com/brrd/electron-tabs/files/9996041/cs1.zip)
this will also show #169. thx!

**Comment by brrd** [comment]
I can't run your code, so I pasted parts of it in electron-tabs demo.

demo/electron-tabs.html:

```html
<!DOCTYPE html>
<html>

<head>
  <title>electron-tabs-demo</title>
</head>
<body style="margin:0">

<tab-group new-tab-button="true" sortable="true">
  <style>
    /* Add custom styles */
    .my-badge {
      background-color: #327BB1;
    }
    .my-custom-tab {
      color: #d135d1;
      font-style: italic;
      font-weight: bold;
    }
  </style>
</tab-group>

<script src="../dist/electron-tabs.js"></script>
<script>
const tabGroup = document.querySelector("tab-group");

let tabInfo = tabGroup.addTab({
    title: "About",
    src: "./info.html",
    webviewAttributes: {
      'webPreferences': 'nodeIntegration=true, contextIsolation=false',
    },
    ready: function(tab) {
      tab.element.classList.add("my-custom-tab");
    },
    visible: true,
    active: true
});
</script>
</body>
</html>
```
 And I copied your info.html in demo/ folder.

As a result everything seems to work as expected (OS info is not printed since I kept nodeIntegration disabled):

![image](https://user-images.githubusercontent.com/7335302/202126175-875149da-e14a-4f07-ae43-edc935a161b8.png)

I don't understand everything in your code, so I can't tell what happens exactly. But obviously this issue is not related with electron-tabs. I advise you to learn javascript and electron first, and to ask your questions to the electron community if needed. I'm sorry to say that I don't have enough time to do this kind of support here.

**Comment by hz2018tv** [comment]
what about #169? it shows up in your demo above too. Understand it may get complicated when things are put together.

**Comment by brrd** [comment]
#169 is the same. I can't replicate this issue neither. I believe it comes from your code, which is over complicated in my opinion. Providing support for electron and javascript is out of the scope of our project.

**Comment by hz2018tv** [comment]
please look at the screenshot of the demo you posted yesterday above, #169 is there. the shaded area does not stop right after the last tab.
