### ISSUE TITLE
webview

### ISSUE THREAD

**Issue by lishihui0613** [brrd/electron-tabs#25]
when addTab，src loads the page,how do I get the elements in webview?

**Comment by brrd** [comment]
What do you want to do exactly? Do you have any code sample?

**Comment by lishihui0613** [comment]
this is webview code in console，<webview class="etabs-view visible" src="http://www.51.com" guestinstace="26">#shadow-root(open)<style>:host{display:flex;}</style>...........
I want to get elements like this <div class="other"><div><img src="./image/other.png" alt=""></div></div>
I don't know if you understand, but I've tried my best.

**Comment by lishihui0613** [comment]
this is webview code in console，<webview class="etabs-view visible" src="http://www.51.com" guestinstace="26">#shadow-root(open)<style>:host{display:flex;}</style>...........
I want to get elements like this <div class="other"><div><img src="./image/other.png" alt=""></div></div>
I don't know if you understand, but I've tried my best.

**Comment by lishihui0613** [comment]
this is webview code in console，```<webview class="etabs-view visible" src="http://www.51.com" guestinstace="26">#shadow-root(open)<style>:host{display:flex;}</style>...........```
I want to get elements like this ```<div class="other"><div><img src="./image/other.png" alt=""></div></div>```
I don't know if you understand, but I've tried my best.

**Comment by lishihui0613** [comment]
How does the WebView element interact with other pages?

**Comment by brrd** [comment]
If I understand, you want to access the elements which are inside the webview.

From electron/electron#3315: 

> Currently there is no way to access DOM elements of webview directly (...)
> In your case you can probably use ipc module to send messages instead.
> You can setup IPC in the preload script.

In order to do this in electron-tabs, you may define a `preload` script in  `options.webviewAttributes` when using `addTab()`.

You will find all the informations about the way to manipulate webviews in electron documentation:
- Documentation about webview preload script: https://electron.atom.io/docs/api/webview-tag/#preload
- About IPC in webview: https://electron.atom.io/docs/api/webview-tag/#webviewsendchannel-arg1-arg2-
- And IPC renderer (to listen to IPC messages in the preload script): https://electron.atom.io/docs/api/ipc-renderer/

I'm closing this issue since it is more related to electron.

**Comment by MEGAMINDMK** [comment]
Electron Tabs webview tag page isnt being loaded but a normal page without webview works
kidnly provide a fix
