### ISSUE TITLE
WebRequest: Request from which Tab?

### ISSUE THREAD

**Issue by Devhercule** [brrd/electron-tabs#35]
Hi, 

I'm using ur module electron-tabs to manage tabs in my Electron application.

I have a quick and urgent question:

I'm using WebRequest to intercept requests
I have only one BrowserWindow with many tabs (webviews).

How is it possible to know from which tab (webview) a request is sent?

Thank you in advance

**Comment by brrd** [comment]
I don't really know webRequest but I can think about 2 options that you could try:

* Use `webRequest `into each tab page so you know that the request comes from the tab were the event handler was set. If you can't modify tab scripts (because you are loading remote URLs), try using [`preload`](https://electron.atom.io/docs/api/webview-tag/#preload)
* Use webview events (such as [`did-get-response-details`](https://electron.atom.io/docs/api/webview-tag/#event-did-get-response-details))

Hope it will help.

**Comment by Devhercule** [comment]
Thank you for your reply.

I want to try the "preload", but i don't know how exactly..

Where can i add prload in your code? i didn't find <webview .....> in your code

Thank you

**Comment by brrd** [comment]
Check #29 (it is the same for `preload`)

**Comment by Devhercule** [comment]
Thanks :)
