### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by DaCardinal** [brrd/electron-tabs#48]
How do I implement JavaScript functions in the webview of electron tabs? What is the correct way?

**Comment by brrd** [comment]
Webviews behave the same than electron webviews, so you can refer to the official documentation: https://electronjs.org/docs/api/webview-tag

If you have access to the page loaded into the webview then you can simply add a `<script>` tag in this page. Otherwise use:

```javascript
tabGroup.addTab({
  webviewAttributes: {
    preload: "./test.js"
  }
});
```

as described in: https://electronjs.org/docs/api/webview-tag#preload
