### ISSUE TITLE
How to use electron-tabs with nodeIntegration disabled?

### ISSUE THREAD

**Issue by gknapp** [brrd/electron-tabs#54]
Due to a [security warning](https://electronjs.org/docs/tutorial/security#2-disable-nodejs-integration-for-remote-content), I've had to disable `webPreferences.nodeIntegration` in the `BrowserWindow` and use a `preload` script. This means `require()` is not defined / available in the renderer thread.

How can I load `electron-tabs` in my renderer thread?

```html
<body>
  <div class="etabs-tabgroup">
    <div class="etabs-tabs"></div>
    <div class="etabs-buttons"></div>
  </div>
  <div class="etabs-views"></div>
  <script>
    const TabGroup = require("electron-tabs");
  </script>
</body>
```

### Error

Line 19:
```js
const TabGroup = require("electron-tabs");
```

```
Uncaught ReferenceError: require is not defined
    at ui.html:19
Cannot read property 'appendChild' of undefined
    at C:\App\node_modules\electron-tabs\index.js:25:45
    at Object.<anonymous> (C:\App\node_modules\electron-tabs\index.js:26:3)
    at Object.<anonymous> (C:\App\node_modules\electron-tabs\index.js:421:3)
    ...
```

Do I have to use SystemJS / Browserify?

**Comment by brrd** [comment]
Currently electron-tabs can not work outside the node context because it relies on `require()` and `EventEmitter`. However what you can do is allowing `nodeIntegration` in BrowserWindow and loading insecure remote content in webviews (in which `nodeIntegration` is disabled by default). See: https://electronjs.org/docs/api/webview-tag#nodeintegration

Actually everything which is loaded in tabs with electron-tabs is rendered in a webview, so it is safe unless you set `webviewAttributes: {  nodeintegration: true  }`.

If you really need to disable node integration in BrowserWindow because for some reason you can not use webviews then you can try with webpack, but remember you will need to polyfill node's `EventEmitter` at some point.

**Comment by gknapp** [comment]
Thanks, I did as suggested and disabled `nodeintegration` on the webview only.
