### ISSUE TITLE
webview.focus causes UI to shift "up"

### ISSUE THREAD

**Issue by GenCodeDev** [brrd/electron-tabs#55]
I'm not exactly sure what is happening, but I've tracked the cause down to line 291 of index.js: `this.webview.focus();`.  With this line in place, I start with this:

![before](https://user-images.githubusercontent.com/35583365/38148137-2e0159a4-3423-11e8-904c-1beb1183e023.png)

which looks fine/correct.
However, as soon as I click on a tab, the UI "shifts" up and I end up with this:

![after](https://user-images.githubusercontent.com/35583365/38148173-569fed8a-3423-11e8-8036-38eb2280942b.png)

Notice how the Angular Material Stepper control  ("Getting Started", "Sites", etc) is only barely visible now under the top blue banner

If I comment out line 291, then the UI doesn't shift and everything appears to work still.

Any idea what is going on?

Thanks!

**Comment by brrd** [comment]
I'm sorry but this is impossible to say with so few information. You have to inspect the page with devtools in order to see what happens in your styles.

Basically what happens when a tab is clicked is:
* "active" class is removed from every tab
* "visible" class is removed from every webview
* clicked tab gets the "active" class
* related webview gets the "visible" class

Source here: https://github.com/brrd/electron-tabs/blob/b17c494e27393fd706f2f6d62d65a19b57c4da00/index.js#L281

Related styles are:

* `.etabs-tab.active` which is defined in the default electron-tabs styles: https://github.com/brrd/electron-tabs/blob/b17c494e27393fd706f2f6d62d65a19b57c4da00/electron-tabs.css#L45
* `webview.visible` which is injected by the script because it is not supposed to be modifed: https://github.com/brrd/electron-tabs/blob/b17c494e27393fd706f2f6d62d65a19b57c4da00/index.js#L7

By checking those elements in devtools you should be able to find what is wrong with your implementation.

Hope this will help you.
