### ISSUE TITLE
How to load asar documents?

### ISSUE THREAD

**Issue by midnight1994** [brrd/electron-tabs#74]
Now I have a requirement to load an electron application when creating a new tab page, in the format of asar. So how do I load it?

**Comment by midnight1994** [comment]
`let tab = tabGroup.addTab({
          title: 'Electron',
          src: './app.asar/dist/electron/index.html',
          visible: true,
          active: true
        })`
I tried to load it like this, but nothing is shown

**Comment by brrd** [comment]
The `src` parameter is actually a simple alias to `<webview>.src` (see https://github.com/electron/electron/blob/master/docs/api/webview-tag.md#src) so tab behavior is basically the same than webview's. 

In other words, using electron-tab as you do is exactly like doing:

```html
<webview src="./app.asar/dist/electron/index.html"></webview>
```

I don't think it's possible to load a file from an asar archive in a webview. I don't really understand why you want to do this, but you will probably have to link to an unpackaged version of `index.html` instead. If you want to package your app in an asar archive, then the common pattern is do it at the end during the build process.

I am closing this issue because it is obviously not specific to electron-tabs. I recommend you ask the question on https://discuss.atom.io/c/electron where you will be more likely to find relevant advice.
